<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<module category="" descriptorversion="1.0" entrypoint="noovi_cloud_solutions/Start" forcesubdialogcall="false" frameworkversion="07.22.10.04" iconlarge="icons/defaultapplicationlg.gif" iconsmall="icons/defaultapplicationsm.gif" modifyInputs="false" modifyOutputs="false" nature="com.avaya.sce.core.speechnature" outputmultipart="false" paramasnamelist="false" provider="" submitmethod="get" version="1.0.0" webname="noovi_cloud_solutions">
    <description/>
    <language name="portuguese" root="en-us"/>
    <dependencies/>
</module>
