package flow.subflow.Subfluxo_5;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 13 DE ABRIL DE 2022 12H36MIN24S BRT
 */
public class loop extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 13 DE ABRIL DE 2022 12H36MIN24S BRT
	 */
	public loop() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 18 DE ABRIL DE 2022 17H11MIN26S BRT
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = null;
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 18 DE ABRIL DE 2022 17H11MIN26S BRT
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();
		variables.add(VariableInfo.createSimpleVariable("number", "0"));
		variables.add(VariableInfo.createSimpleVariable("dimensao", "0"));
		variables.add(VariableInfo.createSimpleVariable("produto", ""));

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 18 DE ABRIL DE 2022 17H11MIN26S BRT
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(3);
		actions.add(new com.avaya.sce.runtime.varoperations.Length("dimensao(L)", "menu5:utterance").setDebugId(14));
		actions.add(new com.avaya.sce.runtime.varoperations.Assign("produto(L)", "audio:", true).setDebugId(15));
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition1", "posicao", com.avaya.sce.runtime.Expression.INT_LESS_THAN, "dimensao(L)", true).setDebugId(16)).evaluate(mySession)) {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.varoperations.SubString("number(L)", "menu5:utterance", "posicao", 1).setDebugId(17));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

			// switch start (19)
			if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition2", "number(L)", com.avaya.sce.runtime.Expression.STRING_EQUAL, "1", false).setDebugId(19)).evaluate(mySession)) {
				actions = new java.util.ArrayList(1);
				actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("produto(L)", "msg022_a", true).setDebugId(20));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition3", "number(L)", com.avaya.sce.runtime.Expression.STRING_EQUAL, "2", false).setDebugId(21)).evaluate(mySession)) {
				actions = new java.util.ArrayList(1);
				actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("produto(L)", "msg022_b", true).setDebugId(22));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition4", "number(L)", com.avaya.sce.runtime.Expression.STRING_EQUAL, "3", false).setDebugId(23)).evaluate(mySession)) {
				actions = new java.util.ArrayList(1);
				actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("produto(L)", "msg022_c", true).setDebugId(24));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition5", "number(L)", com.avaya.sce.runtime.Expression.STRING_EQUAL, "4", false).setDebugId(25)).evaluate(mySession)) {
				actions = new java.util.ArrayList(1);
				actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("produto(L)", "msg022_d", true).setDebugId(26));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition6", "number(L)", com.avaya.sce.runtime.Expression.STRING_EQUAL, "5", false).setDebugId(27)).evaluate(mySession)) {
				actions = new java.util.ArrayList(1);
				actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("produto(L)", "msg022_e", true).setDebugId(28));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition7", "number(L)", com.avaya.sce.runtime.Expression.STRING_EQUAL, "6", false).setDebugId(29)).evaluate(mySession)) {
				actions = new java.util.ArrayList(1);
				actions.add(new com.avaya.sce.runtime.varoperations.Concatenate("produto(L)", "msg022_f", true).setDebugId(30));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;

			}

			actions = new java.util.ArrayList(3);
			actions.add(new com.avaya.sce.runtime.varoperations.AppendToCollection("produtosOpcionais", "produto(L)").setDebugId(31));
			actions.add(new com.avaya.sce.runtime.varoperations.Increment("posicao").setDebugId(32));
			actions.add(new com.avaya.sce.runtime.Next("Subfluxo_5-loop", "loop").setDebugId(33));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else {
			actions = new java.util.ArrayList(6);
			actions.add(new com.avaya.sce.runtime.varoperations.ResetCollection("produtosOpcionais").setDebugId(35));
			actions.add(new com.avaya.sce.runtime.varoperations.NextInCollection("produtosOpcionais").setDebugId(36));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

			for(com.avaya.sce.runtime.VarCollIterator varCollIterator0=(com.avaya.sce.runtime.VarCollIterator)new com.avaya.sce.runtime.VarCollIterator().setDebugId(37);varCollIterator0.hasNext(mySession, "produtosOpcionais");varCollIterator0.next()){
				actions = new java.util.ArrayList(1);
				actions.add(new com.avaya.sce.runtime.tracking.TraceInfo(com.avaya.sce.runtimecommon.ITraceInfo.TRACE_LEVEL_DEBUG, "", "produtosOpcionais").setDebugId(38));
				if(evaluateActions(actions, mySession)) {
					return true;
				}
				actions = null;
			}


			actions = new java.util.ArrayList(3);
			actions.add(new com.avaya.sce.runtime.varoperations.ResetCollection("produtosOpcionais").setDebugId(39));
			actions.add(new com.avaya.sce.runtime.varoperations.NextInCollection("produtosOpcionais").setDebugId(40));
			actions.add(new com.avaya.sce.runtime.Next("Subfluxo_5-speak_plano", "Default").setDebugId(41));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;
		}


		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
}
